apiVersion: v1
kind: ConfigMap
metadata:
  name: named-empty-zone
  namespace: named
data:
  zone: |
    $ORIGIN __ZONE__.
    $TTL 86400
    @         IN  SOA  dns1.__ZONE__.  hostmaster.exphost.pl. (
                  1  ; serial
                  120       ; refresh after 2 minutess
                  120       ; retry after 2 minutes
                  604800      ; expire after 1 week
                  60 )     ; minimum TTL of 1 minutes
    ;
    ;
              IN  NS     dns1.__ZONE__.
    _ext-dns IN TXT "heritage=external-dns,external-dns/owner=k8s___ZONE__,external-dns/resource=ingress/default/placeholder"
    dns1 IN A 127.0.0.2
    _ext-dns.dns1 IN TXT "heritage=external-dns,external-dns/owner=k8s___ZONE__,external-dns/resource=ingress/default/placeholder"
