---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-mixed
  labels:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  annotations:
    lbipam.cilium.io/sharing-key: "shared"
    lbipam.cilium.io/sharing-cross-namespace: "*"
    external-dns.alpha.kubernetes.io/hostname: dns1.{{ .Values.domain }}
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
