apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-tcp
  labels:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: ingress-ip
     external-dns.alpha.kubernetes.io/hostname: ns1.{{ .Values.domain }}
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-udp
  labels:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: ingress-ip
     external-dns.alpha.kubernetes.io/hostname: ns1.{{ .Values.domain }}
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
